/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_calculate_Arith_Order */

#ifndef _Included_com_calculate_Arith_Order
#define _Included_com_calculate_Arith_Order
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_calculate_Arith_Order
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_calculate_Arith_1Order_init
  (JNIEnv *, jobject);

/*
 * Class:     com_calculate_Arith_Order
 * Method:    finalizer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_calculate_Arith_1Order_finalizer
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_calculate_Arith_Order
 * Method:    native_getOrder
 * Signature: (ID)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_calculate_Arith_1Order_native_1getOrder
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     com_calculate_Arith_Order
 * Method:    native_Integer_calculate
 * Signature: (I[II)V
 */
JNIEXPORT jboolean JNICALL Java_com_calculate_Arith_1Order_native_1Integer_1calculate
  (JNIEnv *, jobject, jint, jintArray, jint);

/*
 * Class:     com_calculate_Arith_Order
 * Method:    native_Float_calculate
 * Signature: (I[FI)V
 */
JNIEXPORT jboolean JNICALL Java_com_calculate_Arith_1Order_native_1Float_1calculate
  (JNIEnv *, jobject, jint, jfloatArray, jint);

/*
 * Class:     com_calculate_Arith_Order
 * Method:    native_getRpmState
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_calculate_Arith_1Order_native_1getRpmState
  (JNIEnv * , jobject , jint );
/*
 * Class:     com_calculate_Arith_Order
 * Method:    native_getOrderResultSize
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_calculate_Arith_1Order_native_1getOrderResultSize
  (JNIEnv *, jobject, jint);

///*
// * Class:     com_calculate_Arith_Order
// * Method:    native_setRPMData
// * Signature: (I[FF)V
// */
JNIEXPORT void JNICALL Java_com_calculate_Arith_1Order_native_1setRPMData
  (JNIEnv *, jobject, jint, jfloatArray,jint,jfloat);
/*
 * Class:     com_calculate_Arith_Order
 * Method:    native_getProgress
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_calculate_Arith_1Order_native_1getProgress(
	JNIEnv *, jobject , jint );
#ifdef __cplusplus
}
#endif
#endif
