/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_calculate_Arith_AI */

#ifndef _Included_com_calculate_Arith_AI
#define _Included_com_calculate_Arith_AI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_calculate_Arith_AI
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_calculate_Arith_1AI_init
  (JNIEnv *, jobject);

/*
 * Class:     com_calculate_Arith_AI
 * Method:    finalizer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_calculate_Arith_1AI_finalizer
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_calculate_Arith_AI
 * Method:    native_getAI
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_calculate_Arith_1AI_native_1getAI
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_calculate_Arith_AI
 * Method:    native_calculate
 * Signature: (I[II)V
 */
JNIEXPORT void JNICALL Java_com_calculate_Arith_1AI_native_1calculate
  (JNIEnv *, jobject,jint,jintArray, jint);

/*
 * Class:     com_calculate_Arith_AI
 * Method:    native_getFrame
 * Signature: (II)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_calculate_Arith_1AI_native_1getFrame
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_calculate_Arith_AI
 * Method:    ai_time
 * Signature: (I)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_calculate_Arith_1AI_ai_1time
  (JNIEnv *, jobject, jint,jint);
/*
 * Class:     com_calculate_Arith_AI
 * Method:     native_resetResult
 * Signature: (I[II)V
 */
JNIEXPORT void JNICALL Java_com_calculate_Arith_1AI_native_1resetResult
  (JNIEnv *, jobject,jint);
#ifdef __cplusplus
}
#endif
#endif
