/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_calculate_Arith_OCT */

#ifndef _Included_com_calculate_Arith_OCT
#define _Included_com_calculate_Arith_OCT
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_calculate_Arith_OCT
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_calculate_Arith_1OCT_init
  (JNIEnv *, jobject);

/*
 * Class:     com_calculate_Arith_OCT
 * Method:    native_calculate
 * Signature: (I[II)I
 */
JNIEXPORT jint JNICALL Java_com_calculate_Arith_1OCT_native_1calculate
  (JNIEnv *, jobject, jint, jintArray, jint);

/*
 * Class:     com_calculate_Arith_OCT
 * Method:    native_SetWeightint
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_calculate_Arith_1OCT_native_1SetWeightint
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_calculate_Arith_OCT
 * Method:    native_GetResultInfo
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_calculate_Arith_1OCT_native_1GetResultInfo
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_calculate_Arith_OCT
 * Method:    native_GetResult
 * Signature: (II)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_calculate_Arith_1OCT_native_1GetResult
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_calculate_Arith_OCT
 * Method:    native_GetMeanResult
 * Signature: (II)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_calculate_Arith_1OCT_native_1GetMeanResult
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_calculate_Arith_OCT
 * Method:    native_GetFinalMean
 * Signature: (I[F[FI)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_calculate_Arith_1OCT_native_1GetFinalMean
  (JNIEnv *, jobject, jint, jfloatArray, jint);
/*
 * Class:     com_calculate_Arith_OCT
 * Method:    finalizer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_calculate_Arith_1OCT_finalizer
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_calculate_Arith_OCT
 * Method:    native_setAvarage
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_calculate_Arith_1OCT_native_1setAvarage
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_calculate_Arith_OCT
 * Method:    native_setTimeconstant
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_calculate_Arith_1OCT_native_1setTimeconstant
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     com_calculate_Arith_OCT
 * Method:    native_setTimeinterval
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_calculate_Arith_1OCT_native_1setTimeinterval
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_calculate_Arith_OCT
 * Method:    setWeight
 * Signature: (II[FI)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_calculate_Arith_1OCT_setWeight
  (JNIEnv * , jobject, jint, jint, jfloatArray,jint, jint);
#ifdef __cplusplus
}
#endif
#endif
