/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_calculate_Arith_RPM */

#ifndef _Included_com_calculate_Arith_RPM
#define _Included_com_calculate_Arith_RPM
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_calculate_Arith_RPM
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_calculate_Arith_1RPM_init
  (JNIEnv *, jobject);

/*
 * Class:     com_calculate_Arith_RPM
 * Method:    intiCalc
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_calculate_Arith_1RPM_intiCalc
  (JNIEnv *, jobject);
/*
 * Class:     com_calculate_Arith_RPM
 * Method:    finalizer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_calculate_Arith_1RPM_finalizer
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_calculate_Arith_RPM
 * Method:    native_getRPM
 * Signature: (I)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_calculate_Arith_1RPM_native_1getRPM
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_calculate_Arith_RPM
 * Method:    native_InitTacho
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_com_calculate_Arith_1RPM_native_1InitTacho
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     com_calculate_Arith_RPM
 * Method:    native_DecodeTacho
 * Signature: (I[FI)V
 */
JNIEXPORT void JNICALL Java_com_calculate_Arith_1RPM_native_1DecodeTacho
  (JNIEnv *, jobject, jint, jintArray, jint);

/*
 * Class:     com_calculate_Arith_RPM
 * Method:    native_InitCalcTacho
 * Signature: (ID[FI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_calculate_Arith_1RPM_native_1InitCalcTacho
  (JNIEnv *, jobject, jint, jdouble, jfloatArray, jint);

/*
 * Class:     com_calculate_Arith_RPM
 * Method:    native_HaveRPMData
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_calculate_Arith_1RPM_native_1HaveRPMData
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_calculate_Arith_RPM
 * Method:    native_getRPMRange
 * Signature: (I)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_calculate_Arith_1RPM_native_1getRPMRange
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_calculate_Arith_RPM
 * Method:    native_getRPMFFTData
 * Signature: (I[FD)[F
 */
JNIEXPORT jstring JNICALL Java_com_calculate_Arith_1RPM_native_1getRPMFFTData
  (JNIEnv *, jobject, jint, jobject,jint, jdouble);

/*
 * Class:     com_calculate_Arith_RPM
 * Method:    native_getRPM_AI_SPL_Data
 * Signature: (I[FD)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_calculate_Arith_1RPM_native_1getRPMAIData
  (JNIEnv *, jobject, jint, jfloatArray, jint,jint);

/*
 * Class:     com_calculate_Arith_RPM
 * Method:    native_getRPM_AI_SPL_Data
 * Signature: (I[FD)[F
 */
JNIEXPORT jdoubleArray JNICALL Java_com_calculate_Arith_1RPM_native_1getRPMSPLData
  (JNIEnv *, jobject, jint, jdoubleArray,jint, jint);



#ifdef __cplusplus
}
#endif
#endif
