/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_calculate_Arith_SPL */

#ifndef _Included_com_calculate_Arith_SPL
#define _Included_com_calculate_Arith_SPL
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_calculate_Arith_SPL
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_calculate_Arith_1SPL_init
  (JNIEnv *, jobject);

/*
 * Class:     com_calculate_Arith_SPL
 * Method:    finalizer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_calculate_Arith_1SPL_finalizer
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_calculate_Arith_SPL
 * Method:    native_calculate
 * Signature: (I[II)I
 */
JNIEXPORT jint JNICALL Java_com_calculate_Arith_1SPL_native_1calculate
  (JNIEnv *, jobject, jint, jintArray, jint);


/*
 * Class:     com_calculate_Arith_SPL
 * Method:    native_getResult
 * Signature: (II)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_calculate_Arith_1SPL_native_1getResult
  (JNIEnv *, jobject, jint);


/*
 * Class:     com_calculate_Arith_SPL
 * Method:    native_getInfo
 * Signature: (I)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_calculate_Arith_1SPL_native_1getInfo
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_calculate_Arith_SPL
 * Method:    setWeight
 * Signature: (II)V
 */
JNIEXPORT jint JNICALL Java_com_calculate_Arith_1SPL_setWeight
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_calculate_Arith_SPL
 * Method:    setAva
 * Signature: (II)V
 */
JNIEXPORT jint JNICALL Java_com_calculate_Arith_1SPL_setAva
  (JNIEnv *, jobject, jint, jint);
/*
 * Class:     com_calculate_Arith_SPL
 * Method:    native_resetResult
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_calculate_Arith_1SPL_native_1resetResult
  (JNIEnv *, jobject, jint);
#ifdef __cplusplus
}
#endif
#endif
